export const HELP = [
  "Daedalus CLI",
  "Usage: node apps/cli/src/index.ts <command> [--options]",
  "",
  "Commands:",
  "  lead:create        --tenant <id> --customer <name>",
  "  lead:qualify       --tenant <id> --lead <id>",
  "  lead:discard       --tenant <id> --lead <id> --reason <r>",
  "  proposal:submit    --tenant <id> --proposal <id>",
  "  proposal:reject    --tenant <id> --proposal <id> --reason <r>",
  "  proposal:approve   --tenant <id> --proposal <id>",
  "  proposal:status    --tenant <id> --proposal <id>",
  "  payment:record     --tenant <id> --proposal <id> --payment <id> --amount <n>",
  "  project:create     --tenant <id> --proposal <id>",
  "  project:deliver    --tenant <id> --project <id>",
  "  project:close      --tenant <id> --project <id> [--reason <r>]",
  "  project:status     --tenant <id> --project <id>",
  "  invoice:issue      --tenant <id> --project <id>",
  "  invoice:send       --tenant <id> --invoice <id>",
  "  invoice:pay        --tenant <id> --invoice <id> --payment <id>",
  "  invoice:overdue    --tenant <id> --invoice <id>",
  "  invoice:status     --tenant <id> --invoice <id>",
  "  opportunity:surface  --tenant <id> --label <l> --source <s>",
  "  opportunity:enrich   --tenant <id> --opportunity <id> [--description <d>] [--contact <c>]",
  "  opportunity:qualify  --tenant <id> --opportunity <id>",
  "  opportunity:dismiss  --tenant <id> --opportunity <id> --reason <r>",
  "  opportunity:show     --tenant <id> --opportunity <id>",
  "  opportunity:pipeline  --tenant <id>",
  "  proposal:start  --tenant <id> --lead <id> [--template standard]",
  "  proposal:add-item --tenant <id> --draft <id> --label <l> --amount <n>",
  "  proposal:set-scope --tenant <id> --draft <id> --text <s>",
  "  proposal:show   --tenant <id> --draft <id>",
  "  proposal:finalize --tenant <id> --draft <id>",
  "  proposal:discard  --tenant <id> --draft <id>",
  "  revenue:ingest  --tenant <id>",
  "  revenue:show    --tenant <id>",
  "  revenue:create  --tenant <id> --label <l> --amount <n> [--notes <t>]",
  "  revenue:update  --tenant <id> --estimate <id> [--amount <n>] [--notes <t>]",
  "  revenue:confirm --tenant <id> --estimate <id>",
  "  revenue:receive --tenant <id> --estimate <id>",
  "  expense:register --tenant <id> --label <l> --amount <n>",
  "  revenue:snapshot --tenant <id>",
  "  revenue:summary  --tenant <id>",
  "  revenue:alerts   --tenant <id>",
  "  human:approve   --tenant <id> --workflow <w> --instance <corr>",
  "  human:reject    --tenant <id> --workflow <w> --instance <corr> --reason <r>",
  "  events          --tenant <id>",
].join("\n");

export function renderHelp(): void {
  console.log(HELP);
}
